### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by tshemsedinov** [Trototoo/Kotlin_drawing_app#1]
1. Use intermediate variables to store values to be passed as args in such cases: https://github.com/Trototoo/Kotlin_drawing_app/blob/562c1cbe86b3de29c5c885c13a50d540634cc268/app/src/main/java/com/example/lab5/MainActivity.kt#L21
2. Hardcoded magic numbers: https://github.com/Trototoo/Kotlin_drawing_app/blob/cebb4d891aa359a7e236e98dc85b52dd4e75242c/app/src/main/java/com/example/lab5/shapes/OvalShape.kt#L14-L15
3. Terrible complex long lines, you can put duplicate expressions to intermediate variables https://github.com/Trototoo/Kotlin_drawing_app/blob/cebb4d891aa359a7e236e98dc85b52dd4e75242c/app/src/main/java/com/example/lab5/ShapeCanvas.kt#L78-L81
4. Magic numbers again: https://github.com/Trototoo/Kotlin_drawing_app/blob/cebb4d891aa359a7e236e98dc85b52dd4e75242c/app/src/main/java/com/example/lab5/shapes/Shape.kt#L29
5. We call it pretty columns, you need to invent program abstractions to hide it https://github.com/Trototoo/Kotlin_drawing_app/blob/cebb4d891aa359a7e236e98dc85b52dd4e75242c/app/src/main/java/com/example/lab5/shapes/PointsLineShape.kt#L17-L32
6. Codebase is neither interesting nor complex

**Comment by tshemsedinov** [comment]
You have 80

**Comment by Trototoo** [comment]
Fixed all issues
